name: Create and Publish Release

on:
  push:
    tags:
      - "v*.*.*" # Trigger on version tags like v1.0.0

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Create a zip archive of the repository
      - name: Create ZIP archive
        run: |
          zip -r repository.zip .

      # Publish the release
      - name: Publish Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: BattlegroundCallouts.zip
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
          name: ${{ github.ref_name }} # Release name matches the tag
          body: |
            A new release has been published:
            - Tag: ${{ github.ref_name }}
            - Description: Automated release zip archive.
          draft: false
          prerelease: false
