name: Zip Repository on Main Push

on:
  push:
    branches:
      - main # Trigger only when changes are pushed to the main branch

jobs:
  zip-and-upload:
    name: Zip Repository
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Create a zip archive of the repository
      - name: Create ZIP archive
        run: |
          zip -r repository.zip .

      # Upload the artifact to GitHub Actions
      - name: Upload ZIP as Artifact
        uses: actions/upload-artifact@v3
        with:
          name: repository-zip
          path: repository.zip
